// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_TtKeMlQeaii2ypXiyUzRCi6N_HqVZ1M',
    appId: '1:845032290639:web:14a343c21eaac62599ad3a',
    messagingSenderId: '845032290639',
    projectId: 'dam-u4-asistencia',
    authDomain: 'dam-u4-asistencia.firebaseapp.com',
    storageBucket: 'dam-u4-asistencia.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJAUrJRJ1S01NsCJ8rIJ8wY4WSjwm9Qe0',
    appId: '1:845032290639:android:91bb2e566abacd5f99ad3a',
    messagingSenderId: '845032290639',
    projectId: 'dam-u4-asistencia',
    storageBucket: 'dam-u4-asistencia.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPWWtbIqHiRmwJy6MDBUFSBKLVyyNRv7g',
    appId: '1:845032290639:ios:eb46bdf0d8318bff99ad3a',
    messagingSenderId: '845032290639',
    projectId: 'dam-u4-asistencia',
    storageBucket: 'dam-u4-asistencia.appspot.com',
    iosClientId: '845032290639-9973s76uq7gk4f37j1m8ce7vaolc3ogl.apps.googleusercontent.com',
    iosBundleId: 'com.example.damU4Proyecto2',
  );
}
